services:
  postgres:
    image: postgres:16-alpine
    container_name: conecta-postgres
    environment:
      POSTGRES_USER: conecta_user
      POSTGRES_PASSWORD: conecta_password
      POSTGRES_DB: conecta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conecta-network

  keycloak:

    image: quay.io/keycloak/keycloak:25.0.6
    container_name: conecta-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./docker/keycloak/realm-conecta-ufc.json:/opt/keycloak/data/import/realm-conecta-ufc.json:ro
    networks:
      - conecta-network

  backend:
    build:
      context: ./conecta-ufc-backend
    container_name: conecta-backend
    ports:
      - "8000:8000"
    env_file:
      - ./conecta-ufc-backend/.env
    depends_on:
      - postgres
      - keycloak
    networks:
      - conecta-network

  scrapings:
    build:
      context: ./conecta-ufc-scrapings
    container_name: conecta-scrapings
    ports:
      - "8001:8001"
    env_file:
      - ./conecta-ufc-scrapings/.env
    volumes:
      - ./conecta-ufc-scrapings/data:/app/data
    networks:
      - conecta-network

networks:
  conecta-network:
    driver: bridge

volumes:
  keycloak_data:
  postgres_data:
