"""fix_favoritos_constraints

Revision ID: 2b4c4749821f
Revises: 703e98979337
Create Date: 2026-06-18 11:47:51.153180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4c4749821f'
down_revision: Union[str, Sequence[str], None] = '703e98979337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos') as batch_op:
        batch_op.alter_column('usuario_id',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('oportunidade_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.drop_index('ix_favoritos_usuario_id')
        batch_op.create_unique_constraint('uq_favorito_usuario_oportunidade', ['usuario_id', 'oportunidade_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos') as batch_op:
        batch_op.drop_constraint('uq_favorito_usuario_oportunidade', type_='unique')
        batch_op.create_index('ix_favoritos_usuario_id', ['usuario_id'], unique=False)
        batch_op.alter_column('oportunidade_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('usuario_id',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    # ### end Alembic commands ###
