"""Cria tabelas de oportunidades e resultados

Revision ID: 5e3bd01dfec3
Revises: 
Create Date: 2026-06-13 22:57:34.916579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3bd01dfec3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oportunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('remuneracao', sa.Float(), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_id'), 'oportunidades', ['id'], unique=False)
    op.create_index(op.f('ix_oportunidades_link'), 'oportunidades', ['link'], unique=True)
    op.create_index(op.f('ix_oportunidades_titulo'), 'oportunidades', ['titulo'], unique=False)
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('oportunidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_id'], ['oportunidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_resultados_id'), 'resultados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_id'), table_name='resultados')
    op.drop_table('resultados')
    op.drop_index(op.f('ix_oportunidades_titulo'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_link'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_id'), table_name='oportunidades')
    op.drop_table('oportunidades')
    # ### end Alembic commands ###
