"""cria_tabela_favoritos

Revision ID: 703e98979337
Revises: 5e3bd01dfec3
Create Date: 2026-06-15 18:27:16.798701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703e98979337'
down_revision: Union[str, Sequence[str], None] = '5e3bd01dfec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('oportunidade_id', sa.Integer(), nullable=True),
    sa.Column('data_favoritado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_id'], ['oportunidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favoritos_id'), 'favoritos', ['id'], unique=False)
    op.create_index(op.f('ix_favoritos_usuario_id'), 'favoritos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favoritos_usuario_id'), table_name='favoritos')
    op.drop_index(op.f('ix_favoritos_id'), table_name='favoritos')
    op.drop_table('favoritos')
    # ### end Alembic commands ###
