"""cria_tabela_resultados

Revision ID: 20fe105cf34b
Revises: fb7001220436
Create Date: 2026-05-06 22:33:06.063594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fe105cf34b'
down_revision: Union[str, Sequence[str], None] = 'fb7001220436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_oportunidades')
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('data_fim',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data_publicacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('oportunidade_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_resultados_titulo'))
        batch_op.create_unique_constraint(batch_op.f('uq_resultados_link'), ['link'])
        batch_op.create_foreign_key(batch_op.f('fk_resultados_oportunidade_id_oportunidades'), 'oportunidades', ['oportunidade_id'], ['id'])
        batch_op.drop_column('tipo')
        batch_op.drop_column('resultado')
        batch_op.drop_column('data_fim')
        batch_op.drop_column('data_inicio')
        batch_op.drop_column('origem')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('data_inicio', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('data_fim', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('resultado', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_resultados_oportunidade_id_oportunidades'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_resultados_link'), type_='unique')
        batch_op.create_index(batch_op.f('ix_resultados_titulo'), ['titulo'], unique=False)
        batch_op.drop_column('oportunidade_id')
        batch_op.drop_column('data_publicacao')
        batch_op.drop_column('link')

    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.alter_column('data_fim',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('data_inicio',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_oportunidades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(), nullable=True),
    sa.Column('origem', sa.VARCHAR(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('data_inicio', sa.DATETIME(), nullable=True),
    sa.Column('data_fim', sa.DATETIME(), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
