"""adiciona_remuneracao_e_vagas

Revision ID: 3a42475cc032
Revises: 20fe105cf34b
Create Date: 2026-05-31 14:22:48.498350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a42475cc032'
down_revision: Union[str, Sequence[str], None] = '20fe105cf34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remuneracao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vagas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('vagas')
        batch_op.drop_column('remuneracao')

    # ### end Alembic commands ###
