"""add sincronizado column

Revision ID: f100442d357b
Revises: 3a42475cc032
Create Date: 2026-06-14 12:04:06.741982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f100442d357b'
down_revision: Union[str, Sequence[str], None] = '3a42475cc032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sincronizado', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.drop_column('sincronizado')

    # ### end Alembic commands ###
