"""Tabelas iniciais

Revision ID: fb7001220436
Revises: 
Create Date: 2026-03-31 19:17:13.066890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7001220436'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oportunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.String(), nullable=True),
    sa.Column('data_fim', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_id'), 'oportunidades', ['id'], unique=False)
    op.create_index(op.f('ix_oportunidades_link'), 'oportunidades', ['link'], unique=True)
    op.create_index(op.f('ix_oportunidades_titulo'), 'oportunidades', ['titulo'], unique=False)
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.String(), nullable=True),
    sa.Column('data_fim', sa.String(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_id'), 'resultados', ['id'], unique=False)
    op.create_index(op.f('ix_resultados_titulo'), 'resultados', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_titulo'), table_name='resultados')
    op.drop_index(op.f('ix_resultados_id'), table_name='resultados')
    op.drop_table('resultados')
    op.drop_index(op.f('ix_oportunidades_titulo'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_link'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_id'), table_name='oportunidades')
    op.drop_table('oportunidades')
    # ### end Alembic commands ###
